ALTER TABLE users ADD COLUMN IF NOT EXISTS default_street VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_province VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_district VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_ward VARCHAR(255);
